# 运行环境: prod(实盘) 或 demo(模拟盘)
environment: demo

# 交易循环全局设置
trading:
  poll_interval_sec: 60       # 轮询间隔，秒（默认30秒）
  default_leverage: 100       # 默认杠杆
  default_tp_percent: 0.01    # 止盈30%
  default_sl_percent: 0.01    # 止损20%
  tp_trigger_type: last       # 或 mark/index
  sl_trigger_type: last       # 或 mark/index
  base_notional_usdt: 10      # 每次开仓的本金USDT上限
  margin_mode: cross          # cross 或 isolated
  dry_run: true               # 默认为干跑，避免误下单；命令行 --live 可覆盖
  max_contracts: 1            # 全局最大合约数上限（可选，用于兜底钳制）

# 标的与个性化参数列表
instruments:
  - inst_id: DOGE-USDT-SWAP
    leverage: 20 # 杠杆
    tp_percent: 0.01 # 止盈百分比
    sl_percent: 0.01 # 止损百分比
    base_notional_usdt: 20 # 每次开仓的本金USDT上限
    # 建议限制合约数以免过大（两种方式二选一，优先级：fixed_contracts > max_contracts）
    fixed_contracts: 1
    # max_contracts: 200

# OKX 客户端调试开关
DEBUG_OKX_CLIENT: false

# AI设置（OpenAI 兼容）
ai:
  provider: openai
  model: deepseek-ai/DeepSeek-V3.1

log:
  level: INFO